import "./globals.css";
import { Sora } from "next/font/google";

const sora = Sora({
  family: "Sora",
  subsets: ["latin"],
});


export const metadata = {
  title: "Taskify",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.className}`}>{children}</body>
    </html>
  );
}

